# Generated by Django 6.0.6 on 2026-06-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'HR_DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('desig_id', models.AutoField(primary_key=True, serialize=False)),
                ('desig_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'HR_DESIGNATION',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Employee No')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('joining_date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='DEPT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee.department')),
                ('designation', models.ForeignKey(db_column='DESIG_ID', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee.designation')),
            ],
            options={
                'db_table': 'HR_EMPLOYEE',
                'ordering': ['emp_no'],
            },
        ),
    ]
